[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.141.0"  
  HUGO_ENV = "production"

[context.production.environment]
  HUGO_ENABLEGITINFO = "false"  